version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_for_flask
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/
      - ./web/static:/static
    ports:
      - 1338:80
    depends_on:
      - flask
  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 wsgi:app
    volumes:
      - ./:/var/www
    expose:
      - 8000
    env_file:
      - web/project.env